# Generated by Django 3.0.5 on 2020-04-19 17:18

import datetime
from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerActivity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('work_uuid', models.TextField(unique=True)),
                ('activity', models.TextField()),
                ('created_at', models.DateTimeField(
                    default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('work_uuid', models.CharField(default='', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=20)),
                ('stock_type', models.CharField(default='', max_length=10)),
                ('stock_detail_link', models.CharField(max_length=256)),
                ('current_stock_price', models.FloatField()),
                ('day_increase', models.FloatField()),
                ('fluctuation', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('amount_buying', models.FloatField()),
                ('amount_selling', models.FloatField()),
                ('per', models.FloatField()),
                ('roe', models.FloatField()),
                ('continuous_stock_list', JSONField()),
                ('validation_result', models.BooleanField()),
                ('validation_message', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(
                    default=datetime.datetime.now)),
            ],
        ),
    ]
