# Generated by Django 3.0.5 on 2020-04-21 01:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=20)),
                ('stock_type', models.CharField(max_length=10)),
                ('stock_detail_link', models.CharField(max_length=256)),
                ('current_stock_price', models.FloatField()),
                ('day_increase', models.FloatField()),
                ('fluctuation', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('amount_buying', models.FloatField()),
                ('amount_selling', models.FloatField()),
                ('per', models.FloatField()),
                ('roe', models.FloatField()),
                ('continuous_stock_list', django.contrib.postgres.fields.jsonb.JSONField()),
                ('validation_result', models.BooleanField()),
                ('validation_message', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanager.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanager.Worker')),
            ],
        ),
    ]
