# Generated by Django 3.0.5 on 2020-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=20)),
                ('stock_detail_link', models.CharField(max_length=256)),
                ('validation_message', models.CharField(max_length=256)),
            ],
        ),
    ]
