# Generated by Django 3.0.5 on 2020-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleractivity',
            name='work_uuid',
            field=models.TextField(),
        ),
    ]
