# Generated by Django 3.0.5 on 2020-04-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0002_auto_20200419_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='amount_buying',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='amount_selling',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='continuous_stock_list',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='current_stock_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='day_increase',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fluctuation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='per',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='roe',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='validation_result',
        ),
    ]
