# Generated by Django 3.0.5 on 2020-04-20 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0003_auto_20200420_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount_buying',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='amount_selling',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='continuous_stock_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_stock_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='day_increase',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='fluctuation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='per',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='roe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='validation_result',
            field=models.BooleanField(default=False),
        ),
    ]
