# Generated by Django 3.0.5 on 2020-04-20 02:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0004_auto_20200420_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount_buying',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount_selling',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ask',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='continuous_stock_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_stock_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='day_increase',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fluctuation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='roe',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='validation_result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='work_uuid',
            field=models.CharField(max_length=256),
        ),
    ]
