# Generated by Django 3.0.5 on 2020-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbmanager", "0005_auto_20200420_0254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawleractivity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
