# Generated by Django 3.0.5 on 2020-04-20 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0006_auto_20200420_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleractivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
